## Numpy for Data Analysis

In [1]:
# import section
import numpy as np

In [33]:
# creating array
ar = np.array([100,60,30,40,10])
print("array:",ar)

#2D array 2 x 2 array
arr = np.array([[10,30],[20,40]])
print(arr)

# fill zeros
zer_fill = np.zeros([2,3])
print("Zeros : " ,zer_fill)

ons = np.ones((2,2))
print("Filled Ones : ",ons)

arg = np.arange(1,100,5) # like range(), start/stop/step
print("arrange: ",arg)

lnsp = np.linspace(0,100,5) # evenly spaced points, with stop
print("linespace : ",lnsp)
# arange's stop is exclusive, linspace's stop is inclusive by default.

rand_vals = np.random.rand(3)     # 3 random floats in [0, 1)
print(rand_vals)

dia= np.eye(5) #  5 X 5 matrix diagnol as 1 and else 0 
print("Diagnol : ",dia)

iden = np.identity(5) # similar to eye, creates 5 X 5 matrix diagnol as 1 and else 0 
print("Identity:", iden)

dig = np.diag([3, 5,7]) # creates diagnol matrix with provided values
print("Diagonal:", dig)


array: [100  60  30  40  10]
[[10 30]
 [20 40]]
Zeros :  [[0. 0. 0.]
 [0. 0. 0.]]
Filled Ones :  [[1. 1.]
 [1. 1.]]
arrange:  [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
linespace :  [  0.  25.  50.  75. 100.]
[0.05488076 0.41314534 0.90273614]
Diagnol :  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Identity: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal: [[3 0 0]
 [0 5 0]
 [0 0 7]]


### Array Properties

In [61]:
arr = np.arange(12).reshape(3,4)

print(arr)
print("\n array shape: ",arr.shape)
print(arr.ndim)
print("\n data type : ",arr.dtype)

print("flattened array:" ,arr.flatten())
print("ravel : ",arr.ravel())
print("\n",arr.T)
print(arr.transpose())



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 array shape:  (3, 4)
2

 data type :  int32
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Index and Slicing

In [62]:
print("array : ",arr)
print("\n", arr[0])  # first row (index 0)
print("\n",arr[-1]) # last row (negative indexing counts from the end)

print("\n",arr[1:5])  # rows 1 through 4 (slice: stop index 5 is excluded)

print("\n",arr[:,2])   # all rows, column at index 2 (column slicing)

print("\n",arr[1,:])  # row at index 1, all columns (row slicing)

print("\n",arr[1:3,2:5])  # sub-matrix: rows 1-2 and columns 2-4

array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2 3]

 [ 8  9 10 11]

 [[ 4  5  6  7]
 [ 8  9 10 11]]

 [ 2  6 10]

 [4 5 6 7]

 [[ 6  7]
 [10 11]]
