## Numpy for Data Analysis

In [2]:
# import section
import numpy as np
import csv

In [33]:
# creating array
ar = np.array([100,60,30,40,10])
print("array:",ar)

#2D array 2 x 2 array
arr = np.array([[10,30],[20,40]])
print(arr)

# fill zeros
zer_fill = np.zeros([2,3])
print("Zeros : " ,zer_fill)

ons = np.ones((2,2))
print("Filled Ones : ",ons)

arg = np.arange(1,100,5) # like range(), start/stop/step
print("arrange: ",arg)

lnsp = np.linspace(0,100,5) # evenly spaced points, with stop
print("linespace : ",lnsp)
# arange's stop is exclusive, linspace's stop is inclusive by default.

rand_vals = np.random.rand(3)     # 3 random floats in [0, 1)
print(rand_vals)

dia= np.eye(5) #  5 X 5 matrix diagnol as 1 and else 0 
print("Diagnol : ",dia)

iden = np.identity(5) # similar to eye, creates 5 X 5 matrix diagnol as 1 and else 0 
print("Identity:", iden)

dig = np.diag([3, 5,7]) # creates diagnol matrix with provided values
print("Diagonal:", dig)


array: [100  60  30  40  10]
[[10 30]
 [20 40]]
Zeros :  [[0. 0. 0.]
 [0. 0. 0.]]
Filled Ones :  [[1. 1.]
 [1. 1.]]
arrange:  [ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]
linespace :  [  0.  25.  50.  75. 100.]
[0.05488076 0.41314534 0.90273614]
Diagnol :  [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Identity: [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal: [[3 0 0]
 [0 5 0]
 [0 0 7]]


### Array Properties

In [61]:
arr = np.arange(12).reshape(3,4)

print(arr)
print("\n array shape: ",arr.shape)
print(arr.ndim)
print("\n data type : ",arr.dtype)

print("flattened array:" ,arr.flatten())
print("ravel : ",arr.ravel())
print("\n",arr.T)
print(arr.transpose())



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 array shape:  (3, 4)
2

 data type :  int32
flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## Index and Slicing

In [62]:
print("array : ",arr)
print("\n", arr[0])  # first row (index 0)
print("\n",arr[-1]) # last row (negative indexing counts from the end)

print("\n",arr[1:5])  # rows 1 through 4 (slice: stop index 5 is excluded)

print("\n",arr[:,2])   # all rows, column at index 2 (column slicing)

print("\n",arr[1,:])  # row at index 1, all columns (row slicing)

print("\n",arr[1:3,2:5])  # sub-matrix: rows 1-2 and columns 2-4

array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [0 1 2 3]

 [ 8  9 10 11]

 [[ 4  5  6  7]
 [ 8  9 10 11]]

 [ 2  6 10]

 [4 5 6 7]

 [[ 6  7]
 [10 11]]


## Load the dataset AI Jobs market 2025 and 2026

In [4]:
dataset_path = "../ai_jobs_market_2025_2026.csv"
# Column containers
salary, salary_min, salary_max = [], [], []
years_exp, demand, demand_growth, benefits = [], [], [], []
exp_level, category, country, company_size, salary_tier, skills = [], [], [], [], [], []
is_senior, is_llm, is_remote = [], [], []

with open(dataset_path, newline="", encoding="utf-8") as f:
    reader = csv.DictReader(f)
    for row in reader:
        salary.append(float(row["annual_salary_usd"]))
        salary_min.append(float(row["salary_min_usd"]))
        salary_max.append(float(row["salary_max_usd"]))
        years_exp.append(float(row["years_of_experience"]))
        demand.append(float(row["demand_score"]))
        demand_growth.append(float(row["demand_growth_yoy_pct"]))
        benefits.append(float(row["benefits_score_10"]))

        exp_level.append(row["experience_level"])
        category.append(row["job_category"])
        country.append(row["country"])
        company_size.append(row["company_size"])
        salary_tier.append(row["salary_tier"])
        skills.append(row["required_skills"])

        is_senior.append(int(row["is_senior"]))
        is_llm.append(int(row["is_llm_role"]))
        is_remote.append(int(row["is_remote_friendly"]))

# Convert to typed NumPy arrays
salary = np.array(salary, dtype=np.float64)
salary_min = np.array(salary_min, dtype=np.float64)
salary_max = np.array(salary_max, dtype=np.float64)
years_exp = np.array(years_exp, dtype=np.float64)
demand = np.array(demand, dtype=np.float64)
demand_growth = np.array(demand_growth, dtype=np.float64)
benefits = np.array(benefits, dtype=np.float64)

exp_level = np.array(exp_level, dtype=str)
category = np.array(category, dtype=str)
country = np.array(country, dtype=str)
company_size = np.array(company_size, dtype=str)
salary_tier = np.array(salary_tier, dtype=str)
skills = np.array(skills, dtype=str)

is_senior = np.array(is_senior, dtype=bool)
is_llm = np.array(is_llm, dtype=bool)
is_remote = np.array(is_remote, dtype=bool)

print("Rows loaded:", salary.shape[0])
print("Numeric columns loaded: salary, salary_min, salary_max, years_exp, demand, demand_growth, benefits")
print("Categorical columns loaded: exp_level, category, country, company_size, salary_tier, skills")
print("Boolean columns loaded: is_senior, is_llm, is_remote")

Rows loaded: 1500
Numeric columns loaded: salary, salary_min, salary_max, years_exp, demand, demand_growth, benefits
Categorical columns loaded: exp_level, category, country, company_size, salary_tier, skills
Boolean columns loaded: is_senior, is_llm, is_remote


In [6]:
# 
mean_salary = np.mean(salary)
median_salary = np.median(salary)

# variations
std_salary = np.std(salary)
var_salary = np.var(salary)

# salary range
min_salary = np.min(salary)
max_salary = np.max(salary)
range_salary = np.ptp(salary)          # max - min in one call

# Percentiles 
p25 = np.percentile(salary, 25)
p50 = np.percentile(salary, 50)        # same as median
p75 = np.percentile(salary, 75)
p90 = np.percentile(salary, 90)
iqr = p75 - p25

print(f"Mean:    {mean_salary:,.0f}")
print(f"Median:  {median_salary:,.0f}")
print(f"Std dev: {std_salary:,.0f}")
print(f"Variance:{var_salary:,.0f}")
print(f"Min/Max: {min_salary:,.0f} / ${max_salary:,.0f}")
print(f"Range:   {range_salary:,.0f}")
print(f"\n25th percentile: {p25:,.0f}")
print(f"50th percentile: {p50:,.0f}")
print(f"75th percentile: {p75:,.0f}")
print(f"90th percentile: {p90:,.0f}")
print(f"IQR:             {iqr:,.0f}")

if mean_salary > median_salary:
    print("\nDistribution is right-skewed (high earners pull the mean up)")
else:
    print("\nDistribution is left-skewed or roughly symmetric")

# --- Same stats on demand_score and benefits_score, quickly ---
print(f"\nDemand score  -> mean: {np.mean(demand):.2f}, median: {np.median(demand):.2f}, std: {np.std(demand):.2f}")
print(f"Benefits score -> mean: {np.mean(benefits):.2f}, median: {np.median(benefits):.2f}, std: {np.std(benefits):.2f}")

Mean:    194,892
Median:  180,000
Std dev: 66,485
Variance:4,420,208,603
Min/Max: 90,000 / $384,000
Range:   294,000

25th percentile: 144,750
50th percentile: 180,000
75th percentile: 236,250
90th percentile: 297,100
IQR:             91,500

Distribution is right-skewed (high earners pull the mean up)

Demand score  -> mean: 87.52, median: 89.00, std: 8.02
Benefits score -> mean: 7.90, median: 7.90, std: 1.10


In [9]:
# ---  np.where: condition, value_if_true, value_if_false
salary_flag = np.where(salary > 150000, "High", "Standard")
print(salary_flag[0:10])

# Count how many fall into each category
print("High earners:", np.count_nonzero(salary_flag == "High"))
print("Standard:", np.count_nonzero(salary_flag == "Standard"))

['High' 'High' 'High' 'High' 'High' 'High' 'High' 'High' 'Standard'
 'Standard']
High earners: 1037
Standard: 463


In [14]:
# select 

conditions = [
    salary < 80000,
    (salary >= 80000) & (salary < 130000),
    (salary >= 130000) & (salary < 200000),
    salary >= 200000
]

# Matching labels for each condition, same order
choices = ["Entry", "Mid", "Senior", "Elite"]

#  create new column 
salary_tier = np.select(conditions, choices, default="Unknown")

print("Entry level: ",np.count_nonzero(salary_tier=="Entry"))
print("Mid Level: ", np.count_nonzero(salary_tier=="Mid"))

Entry level:  0
Mid Level:  198


In [15]:
# --- np.sort: returns a sorted COPY of the array ---
sorted_salaries = np.sort(salary)
print("Lowest 5 salaries:", sorted_salaries[:5])
print("Highest 5 salaries:", sorted_salaries[-5:])

# Descending order -- sort ascending, then reverse with [::-1]
sorted_desc = np.sort(salary)[::-1]
print("Top 5 (descending):", sorted_desc[:5])

Lowest 5 salaries: [90000. 90000. 90000. 90000. 90000.]
Highest 5 salaries: [374400. 374400. 384000. 384000. 384000.]
Top 5 (descending): [384000. 384000. 384000. 374400. 374400.]


In [16]:
# unique: just the distinct values 
unique_categories = np.unique(category)
print("Distinct job categories:", unique_categories)
print("Number of distinct categories:", unique_categories.size)

# --- unique + counts together ---
categories, counts = np.unique(category, return_counts=True)

Distinct job categories: ['AI Engineering' 'Architecture' 'Business' 'Data Engineering'
 'Data Science' 'Governance' 'Infrastructure' 'ML Operations' 'Product'
 'Research' 'Robotics' 'Security']
Number of distinct categories: 12
